#!/usr/bin/env bun
/**
 * Go/no-go spike for deployment C (browser owns mic/speaker; host ompx runs
 * signaling + agent).
 *
 * ONE question: does the Codex realtime signaling endpoint accept an SDP offer
 * generated by a real browser (Chrome/Chromium) instead of the native Rust
 * `LiveWebRtcPeer`?
 *
 * How it answers: launch headless Chrome with fake media devices, build the
 * exact offer the browser client would use (RTCPeerConnection + `oai-events`
 * data channel + a mic track), wait for ICE gathering, then POST that SDP
 * through the SAME signaling call `CodexLiveTransport.#signalWithAccess` uses
 * (`packages/coding-agent/src/live/transport.ts:201-234`): same URL, same auth
 * via `withOAuthAccess(..., "openai-codex", ...)`, same header fields as
 * `liveSessionHeaders`, same `{ sdp, session }` body shape.
 *
 * It does NOT open the sideband or start a conversation — it stops the instant
 * signaling returns.
 *
 * Usage:
 *   bun --cwd=packages/coding-agent run scripts/spike-browser-sdp.ts
 *
 * Prints exactly one of:
 *   SPIKE RESULT: PASS status=<2xx> callId=rtc_...
 *   SPIKE RESULT: FAIL status=<code> reason=<bounded body>
 *   SPIKE RESULT: BLOCKED reason=<what is missing>
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { type OAuthAccess, withOAuthAccess } from "@oh-my-pi/pi-ai";
import { getProxyForProvider, wrapFetchForProxy } from "@oh-my-pi/pi-ai/utils/proxy";
import {
	CODEX_BASE_URL,
	CODEX_CLIENT_VERSION,
	getCodexAccountId,
	OPENAI_HEADERS,
} from "@oh-my-pi/pi-catalog/wire/codex";
import { generateCodexAttestation } from "../src/live/attestation";
import { buildLiveSessionPayload } from "../src/live/protocol";
import { parseLiveCallId } from "../src/live/transport";
import { discoverAuthStorage } from "../src/session/auth-broker-config";
import { loadPuppeteer } from "../src/tools/browser/launch";

const LIVE_PROVIDER = "openai-codex";
const LIVE_ORIGINATOR = "Codex Desktop";
const SIGNALING_URL = `${CODEX_BASE_URL}/codex/realtime/calls?intent=quicksilver&architecture=avas`;
const RESPONSE_PREVIEW_CHARS = 300;
const MAX_ERROR_BODY_LENGTH = 2_048;
const ICE_GATHERING_TIMEOUT_MS = 10_000;
const SPIKE_VOICE = "cedar";
const SPIKE_INSTRUCTIONS = "Live remote-voice deployment-C SDP spike. Do not respond.";

/** Browser-side offer builder, mirroring the real deployment-C client. Runs in the page. */
const BROWSER_OFFER_SCRIPT = `(async () => {
	const pc = new RTCPeerConnection();
	pc.createDataChannel("oai-events");
	const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true } });
	for (const track of stream.getAudioTracks()) pc.addTrack(track, stream);
	const offer = await pc.createOffer();
	await pc.setLocalDescription(offer);
	const gathered = Promise.withResolvers();
	if (pc.iceGatheringState === "complete") {
		gathered.resolve();
	} else {
		const timer = setTimeout(gathered.resolve, ${ICE_GATHERING_TIMEOUT_MS});
		pc.addEventListener("icegatheringstatechange", () => {
			if (pc.iceGatheringState === "complete") { clearTimeout(timer); gathered.resolve(); }
		});
	}
	await gathered.promise;
	return {
		sdp: (pc.localDescription && pc.localDescription.sdp) || (offer && offer.sdp) || "",
		iceComplete: pc.iceGatheringState === "complete",
	};
})()`;

/** Result of the browser page building the offer. */
interface BrowserOffer {
	sdp: string;
	iceComplete: boolean;
}

/** Outcome of the single signaling POST. */
interface SignalingOutcome {
	status: number;
	statusText: string;
	location: string | null;
	callId: string | undefined;
	body: string;
}

function boundedBody(body: string, statusText: string): string {
	const normalized = body.trim().replaceAll(/\s+/g, " ");
	if (!normalized) return statusText || "empty response body";
	if (normalized.length <= MAX_ERROR_BODY_LENGTH) return normalized;
	return `${normalized.slice(0, MAX_ERROR_BODY_LENGTH)}…`;
}

/** Mirror `liveSessionHeaders` (transport.ts:79-99) without importing the private helper. */
function buildSignalingHeaders(
	access: OAuthAccess,
	sessionId: string,
	realtimeSessionId: string,
	attestation: string | undefined,
): Record<string, string> {
	const headers: Record<string, string> = {
		Authorization: `Bearer ${access.accessToken}`,
		"OpenAI-Alpha": "quicksilver=v2",
		"User-Agent": `Codex Desktop/${CODEX_CLIENT_VERSION}`,
		"x-session-id": realtimeSessionId,
		[OPENAI_HEADERS.ORIGINATOR]: LIVE_ORIGINATOR,
		[OPENAI_HEADERS.VERSION]: CODEX_CLIENT_VERSION,
		[OPENAI_HEADERS.SCOPED_SESSION_ID]: sessionId,
		[OPENAI_HEADERS.THREAD_ID]: sessionId,
	};
	const accountId = access.accountId ?? getCodexAccountId(access.accessToken);
	if (accountId) headers[OPENAI_HEADERS.ACCOUNT_ID] = accountId;
	if (attestation) headers["x-oai-attestation"] = attestation;
	return headers;
}

/** Locate a usable Chrome/Chromium binary in the assignment's declared order. Returns [path, checkedLog]. */
function findChrome(): { chromePath: string | undefined; checked: string[] } {
	const checked: string[] = [];

	const envPath = process.env.PUPPETEER_EXECUTABLE_PATH;
	checked.push(`PUPPETEER_EXECUTABLE_PATH=${envPath ? envPath : "(unset)"}`);
	if (envPath && isExecutable(envPath)) return { chromePath: envPath, checked };

	const cacheDir = path.join(os.homedir(), ".omp", "puppeteer");
	const cacheHit = findChromeInDir(cacheDir);
	checked.push(`~/.omp/puppeteer -> ${cacheHit ?? "(no chrome binary)"}`);
	if (cacheHit) return { chromePath: cacheHit, checked };

	for (const name of ["google-chrome", "chromium", "chrome", "chromium-browser", "google-chrome-stable"]) {
		const found = Bun.which(name);
		checked.push(`PATH ${name} -> ${found ?? "(not found)"}`);
		if (found) return { chromePath: found, checked };
	}

	return { chromePath: undefined, checked };
}

function isExecutable(candidate: string): boolean {
	try {
		return fs.statSync(candidate).isFile();
	} catch {
		return false;
	}
}

/** Shallow walk of a puppeteer cache dir for an installed `chrome` executable. */
function findChromeInDir(dir: string): string | undefined {
	let entries: fs.Dirent[];
	try {
		entries = fs.readdirSync(dir, { withFileTypes: true, recursive: true });
	} catch {
		return undefined;
	}
	for (const entry of entries) {
		if (!entry.isFile()) continue;
		if (entry.name !== "chrome" && entry.name !== "chrome-headless-shell") continue;
		const full = path.join(entry.parentPath ?? dir, entry.name);
		if (isExecutable(full)) return full;
	}
	return undefined;
}

/** Print the m= and a=rtpmap control lines so a human can diff codecs vs the native offer. */
function printOfferControlLines(sdp: string): void {
	const lines = sdp.split(/\r?\n/).filter(line => line.startsWith("m=") || line.startsWith("a=rtpmap"));
	console.log("--- browser offer control lines (m= / a=rtpmap) ---");
	for (const line of lines) console.log(line);
	console.log("--- end control lines ---");
}

/** Generate a browser SDP offer via headless Chrome. */
async function generateBrowserOffer(chromePath: string): Promise<BrowserOffer> {
	const puppeteer = await loadPuppeteer();
	// http://127.0.0.1 is a secure context, so navigator.mediaDevices is available;
	// the fake device flags then satisfy getUserMedia without real hardware.
	const server = Bun.serve({
		port: 0,
		hostname: "127.0.0.1",
		fetch: () =>
			new Response("<!doctype html><meta charset=utf-8><title>sdp-spike</title>", {
				headers: { "content-type": "text/html" },
			}),
	});
	const browser = await puppeteer.launch({
		headless: true,
		executablePath: chromePath,
		args: [
			"--use-fake-ui-for-media-stream",
			"--use-fake-device-for-media-stream",
			"--autoplay-policy=no-user-gesture-required",
			// container launchability; does not affect the produced SDP:
			"--no-sandbox",
			"--disable-setuid-sandbox",
		],
	});
	try {
		const page = await browser.newPage();
		await page.goto(`http://127.0.0.1:${server.port}/`, { waitUntil: "load" });
		const offer = (await page.evaluate(BROWSER_OFFER_SCRIPT)) as BrowserOffer;
		return offer;
	} finally {
		await browser.close().catch(() => undefined);
		server.stop(true);
	}
}

/** POST the browser SDP through the real Codex signaling call. */
async function signal(sdp: string): Promise<SignalingOutcome> {
	const sessionId = crypto.randomUUID();
	const realtimeSessionId = crypto.randomUUID();
	const attestation = await generateCodexAttestation();
	console.log(`attestation: ${attestation ? "present" : "omitted (expected off macOS/arm64)"}`);
	const authStorage = await discoverAuthStorage();
	const fetchImpl = wrapFetchForProxy(fetch, LIVE_PROVIDER);
	const proxy = getProxyForProvider(LIVE_PROVIDER);
	if (proxy) console.log(`proxy: ${proxy}`);

	return await withOAuthAccess(
		authStorage,
		LIVE_PROVIDER,
		async access => {
			const headers = new Headers({
				...buildSignalingHeaders(access, sessionId, realtimeSessionId, attestation),
				Accept: "*/*",
				"Content-Type": "application/json",
			});
			const response = await fetchImpl(SIGNALING_URL, {
				method: "POST",
				headers,
				body: JSON.stringify({ sdp, session: buildLiveSessionPayload(SPIKE_INSTRUCTIONS, SPIKE_VOICE) }),
			});
			const body = await response.text();
			const location = response.headers.get("location");
			return {
				status: response.status,
				statusText: response.statusText,
				location,
				callId: parseLiveCallId(location),
				body,
			};
		},
		{ sessionId, missingAccessMessage: "No Codex OAuth credential is available for a live call." },
	);
}

async function main(): Promise<void> {
	const { chromePath, checked } = findChrome();
	console.log("--- chrome detection ---");
	for (const line of checked) console.log(line);
	console.log("--- end detection ---");
	if (!chromePath) {
		console.log(`SPIKE RESULT: BLOCKED reason=no Chrome/Chromium binary found (checked: ${checked.join("; ")})`);
		process.exitCode = 1;
		return;
	}
	console.log(`using chrome: ${chromePath}`);

	let offer: BrowserOffer;
	try {
		offer = await generateBrowserOffer(chromePath);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.log(`SPIKE RESULT: BLOCKED reason=browser offer generation failed: ${boundedBody(message, "")}`);
		process.exitCode = 1;
		return;
	}
	if (!offer.sdp.trim()) {
		console.log("SPIKE RESULT: BLOCKED reason=browser produced an empty SDP offer");
		process.exitCode = 1;
		return;
	}
	if (!offer.iceComplete) {
		console.log(
			`ICE gathering did not complete within ${ICE_GATHERING_TIMEOUT_MS}ms; proceeding with partial candidates.`,
		);
	}
	console.log(`browser offer: ${offer.sdp.length} bytes, iceComplete=${offer.iceComplete}`);
	printOfferControlLines(offer.sdp);

	let outcome: SignalingOutcome;
	try {
		outcome = await signal(offer.sdp);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.log(`SPIKE RESULT: BLOCKED reason=${boundedBody(message, "")}`);
		process.exitCode = 1;
		return;
	}

	console.log(`HTTP status: ${outcome.status} ${outcome.statusText}`);
	console.log(`Location header: ${outcome.location ?? "(none)"}`);
	console.log(`parsed callId: ${outcome.callId ?? "(none)"}`);
	console.log(
		`response body (first ${RESPONSE_PREVIEW_CHARS} chars): ${outcome.body.slice(0, RESPONSE_PREVIEW_CHARS)}`,
	);

	const ok = outcome.status >= 200 && outcome.status < 300;
	if (ok && outcome.callId) {
		console.log(`SPIKE RESULT: PASS status=${outcome.status} callId=${outcome.callId}`);
		return;
	}
	if (ok && !outcome.callId) {
		console.log(
			`SPIKE RESULT: FAIL status=${outcome.status} reason=2xx but no rtc_* call id in Location: ${outcome.location ?? "(none)"}`,
		);
		process.exitCode = 1;
		return;
	}
	console.log(`SPIKE RESULT: FAIL status=${outcome.status} reason=${boundedBody(outcome.body, outcome.statusText)}`);
	process.exitCode = 1;
}

await main();
