import * as fs from "node:fs/promises";
import * as path from "node:path";

interface GeneratedAsset {
	key: string;
	file: string;
	contentType: string;
	cacheControl?: string;
	binary?: boolean;
}

const packageRoot = path.resolve(import.meta.dir, "..");
const temporaryDirectory = path.join(packageRoot, ".kanban-build");
const distributionDirectory = path.join(packageRoot, "dist", "kanban");
const generatedModule = path.resolve(
	packageRoot,
	"..",
	"coding-agent",
	"src",
	"kanban",
	"client",
	"assets.generated.ts",
);

const assets: GeneratedAsset[] = [
	{
		key: "/",
		file: path.join(packageRoot, "kanban.html"),
		contentType: "text/html; charset=utf-8",
		cacheControl: "no-cache",
	},
	{
		key: "/app.js",
		file: path.join(temporaryDirectory, "app.js"),
		contentType: "text/javascript; charset=utf-8",
		cacheControl: "no-cache",
	},
	{
		key: "/app.css",
		file: path.join(temporaryDirectory, "app.css"),
		contentType: "text/css; charset=utf-8",
		cacheControl: "no-cache",
	},
	{
		key: "/manifest.webmanifest",
		file: path.join(packageRoot, "public", "kanban", "manifest.webmanifest"),
		contentType: "application/manifest+json; charset=utf-8",
		cacheControl: "no-cache",
	},
	{
		key: "/sw.js",
		file: path.join(packageRoot, "public", "kanban", "sw.js"),
		contentType: "text/javascript; charset=utf-8",
		cacheControl: "no-cache",
	},
	{
		key: "/favicon.svg",
		file: path.join(packageRoot, "public", "favicon.svg"),
		contentType: "image/svg+xml",
		cacheControl: "public, max-age=31536000, immutable",
	},
	{
		key: "/favicon-180x180.png",
		file: path.join(packageRoot, "public", "favicon-180x180.png"),
		contentType: "image/png",
		cacheControl: "public, max-age=31536000, immutable",
		binary: true,
	},
	{
		key: "/favicon-192x192.png",
		file: path.join(packageRoot, "public", "favicon-192x192.png"),
		contentType: "image/png",
		cacheControl: "public, max-age=31536000, immutable",
		binary: true,
	},
	{
		key: "/favicon-512x512.png",
		file: path.join(packageRoot, "public", "favicon-512x512.png"),
		contentType: "image/png",
		cacheControl: "public, max-age=31536000, immutable",
		binary: true,
	},
];

function byteArrayLiteral(bytes: Uint8Array): string {
	return `new Uint8Array([${bytes.join(",")}])`;
}

function normalizedText(bytes: Uint8Array): string {
	const text = new TextDecoder().decode(bytes).replaceAll("\r\n", "\n");
	return text.endsWith("\n") ? text : `${text}\n`;
}

async function generateAssetModule(): Promise<void> {
	const entries: string[] = [];
	for (const asset of assets) {
		const bytes = await Bun.file(asset.file).bytes();
		const body = asset.binary ? byteArrayLiteral(bytes) : JSON.stringify(normalizedText(bytes));
		const cacheControl = asset.cacheControl ? `, cacheControl: ${JSON.stringify(asset.cacheControl)}` : "";
		entries.push(
			`\t${JSON.stringify(asset.key)}: { body: ${body}, contentType: ${JSON.stringify(asset.contentType)}${cacheControl} },`,
		);
	}
	const source = [
		"/* This file is generated by packages/collab-web/scripts/build-kanban.ts. */",
		"export const KANBAN_CLIENT_ASSETS: Readonly<Record<string, { body: string | Uint8Array; contentType: string; cacheControl?: string }>> = Object.freeze({",
		...entries,
		"});",
		"",
	].join("\n");
	await fs.mkdir(path.dirname(generatedModule), { recursive: true });
	await Bun.write(generatedModule, source);
}

async function writeDistribution(): Promise<void> {
	await fs.rm(distributionDirectory, { recursive: true, force: true });
	await fs.mkdir(distributionDirectory, { recursive: true });
	for (const asset of assets) {
		const outputName = asset.key === "/" ? "index.html" : asset.key.slice(1);
		await Bun.write(path.join(distributionDirectory, outputName), await Bun.file(asset.file).bytes());
	}
}

await fs.rm(temporaryDirectory, { recursive: true, force: true });
await fs.mkdir(temporaryDirectory, { recursive: true });
try {
	const result = await Bun.build({
		entrypoints: [path.join(packageRoot, "src", "kanban", "main.tsx")],
		outdir: temporaryDirectory,
		target: "browser",
		format: "esm",
		splitting: false,
		minify: true,
		sourcemap: "none",
		naming: {
			entry: "app.[ext]",
			chunk: "[name]-[hash].[ext]",
			asset: "[name]-[hash].[ext]",
		},
	});
	if (!result.success) {
		for (const log of result.logs) process.stderr.write(`${log.message}\n`);
		throw new Error("Kanban browser bundle failed");
	}
	await generateAssetModule();
	await writeDistribution();
} finally {
	await fs.rm(temporaryDirectory, { recursive: true, force: true });
}
